#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $API_POSTGRES_USER WITH PASSWORD '$API_POSTGRES_PASSWORD';
    CREATE DATABASE task_list;
    GRANT ALL PRIVILEGES ON DATABASE task_list TO $API_POSTGRES_USER;
EOSQL