apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-list-deployment
  labels:
    app: task-list
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: task-list
  template:
    metadata:
      labels:
        app: task-list
    spec:
      hostNetwork: true
      containers:
      {{- range .Values.different_images }}
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          {{ if .environment }}
          env:
            {{- range .environment }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          {{ end }}
      {{- end }}
