replicaCount: 1

app: task-list
tier: database

postgresUser: postgres
postgresPassword: postgres
postgresDB: postgres
pgData: /var/lib/postgresql/data/pgdata
localData: /home/ubuntu/task-list/data
apiPostgresUser: apiuser
apiPostgresPassword: apipassword
